Update core.py
When I want to use a lambda function in python like this one :

'extract_content = lambda url: trafilatura.extract(trafilatura.fetch_url(url), output_format='html', include_links=True)'


I encounter the following error: 

'AttributeError: 'lxml.etree._Element' object has no attribute 'text_content''

Indeed, in the trafilatura library, the text_content() method is used to extract the text from the _Element object of lxml.etree. We can get the same result by using the etree.tostring() method with the argument method='text'.

So in the compare_extraction function of trafilatura/core.py, I replaced this line :

'algo_text = trim(temppost_algo.text_content())'

with this line: 

'algo_text = trim(etree.tostring(temppost_algo, method='text', encoding='utf-8').decode('utf-8'))'


Don't forget to import etree in core.py

'from lxml import etree'

Tested and working